---
- hosts: moodle_server
  become: yes
  become_user: root
  become_method: su
  tasks:
    - name: Update apt repos
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    
    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Install necessary packages
      apt:
        pkg:
        - graphviz 
        - aspell 
        - ghostscript 
        - clamav 
        - git  

